### ISSUE TITLE
Doesn't connect

### ISSUE THREAD

**Issue by ALEEF02** [KonradIT/HEROPebble#1]
When I have my hero session Wi-Fi connected, the watch app says it's not connected

**Comment by KonradIT** [comment]
Hey @ALEEF02 make sure you first go to the GoPro App and get a live preview of what the camera is seeing, then close the app, connect to the GoPro Wifi again and open the pebble app

**Comment by jkngale** [comment]
Hello!!

The app looks great but are you planning on making it work with gopro hero 3? 

Thanks!

**Comment by KonradIT** [comment]
@galesberdurin hi, yeah, I am dealing now with HERO5 API but when I get it on a stable track I will continue with the Pebble App, I will be adding support for HERO3, 3+ and HERO+ LCD and HERO+

**Comment by filipkowicz** [comment]
@KonradIT Hi, I have gopro hero 4 with software 4.02.05.00.00, app is 3.0.3277 
Cant connect in any configuration. With app launched, or without - still connected to Gopro Wifi.

do you have any idea what could be RC ?

**Comment by filipkowicz** [comment]
what strange when I manually make calls from https://github.com/KonradIT/goprowifihack/blob/master/HERO4/WifiCommands.md

everything works

**Comment by KonradIT** [comment]
Hi @filipkowicz , what HERO4 do you have? HERO4 Silver, Black or Session?
