### ISSUE TITLE
Application out of date on the Pebble app store

### ISSUE THREAD

**Issue by MFava91** [KonradIT/HEROPebble#2]
Hi @KonradIT!
I have a Hero 5 and a Pebble 2 and when I've installed your application from the Pebble app store I had some connection problems.
So I've found this repo, I've built the app from source and all work fine. 
I suspect that the app on the Pebble app store isn't updated (v1.1 on Pebble app store, v1.2 on the _package.json_).
Can you check it and update if needed?

p.s. Thanks for your amazing app.

**Comment by KonradIT** [comment]
Hi, I just got a H5 a few days ago and I'm working on an update,I'll push it when it's finished.

**Comment by tuanathon** [comment]
Hi. I am having issues connecting my Pebble 2 with Hero5, is this a known issue?

**Comment by KonradIT** [comment]
@tuanathon @MFava91 sorry for the delay, just updated the repo, will do app store update now. [commit id](https://github.com/KonradIT/HEROPebble/commit/685ede54c519019afddc607dda21451e710c3539)
